FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY requirements_api.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements_api.txt

COPY api.py .
COPY scrape_and_summarize.py .
COPY config.py .
COPY save_bucket.py .
COPY logger_utils.py .

CMD ["python3", "-u", "api.py"]