FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gcc libfreetype6-dev && \
    apt-get clean

COPY config/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY config/ ./config/
COPY data/ ./data/

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.scraper.scrape_and_summarize"]
